version: '2'
services:
    studentmining-app:
        image: studentmining
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@studentmining-oracle:1521:StudentMining
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://studentmining-elasticsearch:9200
        ports:
            - 8080:8080
    studentmining-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: studentmining-elasticsearch
